# Tugas 2

1. Carilah data yang bertipe numerik ( data klassifikasi)
2. Lakukan proses diskritisasi dengan *equal width* dan *equal frequency*
3. Lakukan proses diskritisasi dengan basis *entropy*
4. Kumpulkan tugas dengan link github ( web statis dari jupyter book)


## **Cari data**

sumber
[Data Bunga Iris](https://raw.githubusercontent.com/HanifSantoso05/dataset_matkul/main/Iris.csv)

In [87]:
import pandas as pd
import numpy as np

In [88]:
# source data
dataset_url = "https://raw.githubusercontent.com/Alfito12/dataset/main/iris.csv"

In [89]:
# Create dataframe
df = pd.read_csv(dataset_url)

In [90]:
# Menampilkan dataset iris
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [91]:
# show first 15 rows
df.head(10)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [92]:
# CONSTAN SERIES

SEPAL_LENGTH_SERIES = df["sepal.length"]
SEPAL_WIDTH_SERIES = df["sepal.width"]
PETAL_LENGTH_SERIES = df["petal.length"]
PETAL_WIDTH_SERIES = df["petal.width"]

## **Hitung Data**

### Definisi *discretization*

1. Proses mengubah data bertipe data *numeric* menjadi data bertipe *categorical*
2. Diskritisasi memiliki 2 pendekatan yaitu *equal-width intervals* dan *equal-frequency intervals*
3. *equal-width intervals* adalah diskritisasi dengan lebar data yang sama
4. *equal-frequency intervals* adalah diskritisasi dengan jumlah data yang sama

#### 2. Lakukan proses diskritisasi dengan *equal width* dan *equal frequency*

##### Cut

2. Lakukan proses diskritisasi dengan *equal width* dan *equal frequency*


```
# Syntax
pd.cut(series, interval, right=True, label)
```

###### Sepal Width

* Equal Width Intervals lebar kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [28]:
# equal-width intervals

labels = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
amount_of_binning = len(labels)

sepal_width_ew_binning = pd.cut(SEPAL_WIDTH_SERIES, amount_of_binning, True, labels)
labelled_sepal_width_ew_binning = sepal_width_ew_binning.value_counts()
interval_sepal_width_ew_binning = pd.cut(SEPAL_WIDTH_SERIES, amount_of_binning, True).value_counts()

In [29]:
# dataframe of sepal-width and sepal category
pd.concat((SEPAL_WIDTH_SERIES, sepal_width_ew_binning), axis=1)

    sepal.width    sepal.width
0           3.5          Lebar
1           3.0          Lebar
2           3.2          Lebar
3           3.1          Lebar
4           3.6          Lebar
..          ...            ...
145         3.0          Lebar
146         2.5  Sedikit Lebar
147         3.0          Lebar
148         3.4          Lebar
149         3.0          Lebar

[150 rows x 2 columns]

In [36]:
# equal-width intervals binning with label
labelled_sepal_width_ew_binning

Lebar            88
Sedikit Lebar    47
Sangat Lebar     15
Name: sepal.width, dtype: int64

In [35]:
# equal-width intervals without label
interval_sepal_width_ew_binning

(2.8, 3.6]      88
(1.998, 2.8]    47
(3.6, 4.4]      15
Name: sepal.width, dtype: int64

###### Petal Width

* Equal Width Intervals lebar mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [43]:
# equal-width intervals
labels = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
amount_of_binning = len(labels)

petal_width_ew_binning = pd.cut(PETAL_WIDTH_SERIES, amount_of_binning, True, labels)
labelled_petal_width_ew_binning = petal_width_ew_binning.value_counts()
interval_petal_width_ew_binning = pd.cut(PETAL_WIDTH_SERIES, amount_of_binning, True).value_counts()

In [44]:
# dataframe of petal-width and petal category
pd.concat((PETAL_WIDTH_SERIES, petal_width_ew_binning), axis=1)

    petal.width    petal.width
0           0.2  Sedikit Lebar
1           0.2  Sedikit Lebar
2           0.2  Sedikit Lebar
3           0.2  Sedikit Lebar
4           0.2  Sedikit Lebar
..          ...            ...
145         2.3   Sangat Lebar
146         1.9   Sangat Lebar
147         2.0   Sangat Lebar
148         2.3   Sangat Lebar
149         1.8   Sangat Lebar

[150 rows x 2 columns]

In [45]:
# equal-width intervals with label
labelled_petal_width_ew_binning

Lebar            54
Sedikit Lebar    50
Sangat Lebar     46
Name: petal.width, dtype: int64

In [47]:
# equal-width intervals without label
interval_petal_width_ew_binning

(0.9, 1.7]       54
(0.0976, 0.9]    50
(1.7, 2.5]       46
Name: petal.width, dtype: int64

###### Sepal Length

* Equal Width Intervals panjang kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [49]:
# equal-width intervals

labels = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
amount_of_binning = len(labels)

sepal_length_ew_binning = pd.cut(SEPAL_LENGTH_SERIES, amount_of_binning, True, labels)
labelled_sepal_length_ew_binning = sepal_length_ew_binning.value_counts()
interval_sepal_length_ew_binning = pd.cut(SEPAL_LENGTH_SERIES, amount_of_binning, True).value_counts()

In [50]:
# dataframe of sepal-width and sepal category
pd.concat((SEPAL_LENGTH_SERIES, sepal_length_ew_binning), axis=1)

    sepal.length   sepal.length
0            5.1  Sedikit Lebar
1            4.9  Sedikit Lebar
2            4.7  Sedikit Lebar
3            4.6  Sedikit Lebar
4            5.0  Sedikit Lebar
..           ...            ...
145          6.7          Lebar
146          6.3          Lebar
147          6.5          Lebar
148          6.2          Lebar
149          5.9          Lebar

[150 rows x 2 columns]

In [51]:
# equal-width intervals with label
labelled_sepal_length_ew_binning

Lebar            71
Sedikit Lebar    59
Sangat Lebar     20
Name: sepal.length, dtype: int64

In [52]:
# equal-width intervals without label
interval_sepal_length_ew_binning

(5.5, 6.7]      71
(4.296, 5.5]    59
(6.7, 7.9]      20
Name: sepal.length, dtype: int64

###### Petal Length

* Equal Width Intervals panjang mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [53]:
# equal-width intervals
labels = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
amount_of_binning = len(labels)

petal_length_ew_binning = pd.cut(PETAL_LENGTH_SERIES, amount_of_binning, True, labels)
labelled_petal_length_ew_binning = petal_length_ew_binning.value_counts()
interval_petal_length_ew_binning = pd.cut(PETAL_LENGTH_SERIES, amount_of_binning, True).value_counts()

In [54]:
# dataframe of petal-width and petal category
pd.concat((PETAL_LENGTH_SERIES,petal_length_ew_binning), axis=1)

    petal.length   petal.length
0            1.4  Sedikit Lebar
1            1.4  Sedikit Lebar
2            1.3  Sedikit Lebar
3            1.5  Sedikit Lebar
4            1.4  Sedikit Lebar
..           ...            ...
145          5.2   Sangat Lebar
146          5.0   Sangat Lebar
147          5.2   Sangat Lebar
148          5.4   Sangat Lebar
149          5.1   Sangat Lebar

[150 rows x 2 columns]

In [55]:
# equal-width intervals binning with label
labelled_petal_length_ew_binning

Lebar            54
Sedikit Lebar    50
Sangat Lebar     46
Name: petal.length, dtype: int64

In [56]:
# equal-width intervals out label
interval_petal_length_ew_binning

(2.967, 4.933]    54
(0.994, 2.967]    50
(4.933, 6.9]      46
Name: petal.length, dtype: int64

##### Qcut
* Qcut adalah sebuah *method* pada library *pandas* untuk melakukan perhitungan *equal frequency intervals*

```
# Syntax
pd.qcut(series, interval, label)
```

###### Sepal Width

* Equal Frequency Intervals lebar kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [57]:
# equal-frequency intervals

labels = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
amount_of_binning = len(labels)

sepal_width_ef_binning = pd.qcut(SEPAL_WIDTH_SERIES, amount_of_binning, labels)
labelled_sepal_width_ef_binning = sepal_width_ef_binning.value_counts()
interval_sepal_width_ef_binning = pd.qcut(SEPAL_WIDTH_SERIES, amount_of_binning).value_counts()

In [58]:
# dataframe of sepal-width and sepal category
pd.concat((SEPAL_WIDTH_SERIES, sepal_width_ef_binning), axis = 1)

    sepal.width    sepal.width
0           3.5   Sangat Lebar
1           3.0          Lebar
2           3.2          Lebar
3           3.1          Lebar
4           3.6   Sangat Lebar
..          ...            ...
145         3.0          Lebar
146         2.5  Sedikit Lebar
147         3.0          Lebar
148         3.4   Sangat Lebar
149         3.0          Lebar

[150 rows x 2 columns]

In [59]:
# equal-frequency intervals binning with label
labelled_sepal_width_ef_binning

Sedikit Lebar    57
Lebar            50
Sangat Lebar     43
Name: sepal.width, dtype: int64

In [60]:
# equal-frequency intervals out label
interval_sepal_width_ef_binning

(1.999, 2.9]    57
(2.9, 3.2]      50
(3.2, 4.4]      43
Name: sepal.width, dtype: int64

###### Petal Width

* Equal Frequency Intervals lebar mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [61]:
# equal-frequency intervals

labels = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
amount_of_binning = len(labels)

petal_width_ef_binning = pd.qcut(PETAL_WIDTH_SERIES, amount_of_binning, labels)
labelled_petal_width_ef_binning = petal_width_ef_binning.value_counts()
interval_petal_width_ef_binning = pd.qcut(PETAL_WIDTH_SERIES, amount_of_binning).value_counts()

In [62]:
# dataframe of petal-width and petal category
pd.concat((PETAL_WIDTH_SERIES, petal_width_ef_binning), axis = 1)

    petal.width    petal.width
0           0.2  Sedikit Lebar
1           0.2  Sedikit Lebar
2           0.2  Sedikit Lebar
3           0.2  Sedikit Lebar
4           0.2  Sedikit Lebar
..          ...            ...
145         2.3   Sangat Lebar
146         1.9   Sangat Lebar
147         2.0   Sangat Lebar
148         2.3   Sangat Lebar
149         1.8   Sangat Lebar

[150 rows x 2 columns]

In [63]:
# equal-frequency intervals binning with label
labelled_petal_width_ef_binning

Lebar            52
Sedikit Lebar    50
Sangat Lebar     48
Name: petal.width, dtype: int64

In [64]:
# equal-frequency intervals without label
interval_petal_width_ef_binning

(0.867, 1.6]      52
(0.099, 0.867]    50
(1.6, 2.5]        48
Name: petal.width, dtype: int64

###### Sepal Length

* Equal Frequency Intervals panjang kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [65]:
# equal-frequency intervals

labels = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
amount_of_binning = len(labels)

sepal_length_ef_binning = pd.qcut(SEPAL_LENGTH_SERIES, amount_of_binning, labels)
labelled_sepal_length_ef_binning = sepal_length_ef_binning.value_counts()
interval_sepal_length_ef_binning = pd.qcut(SEPAL_LENGTH_SERIES, amount_of_binning).value_counts()

In [66]:
# dataframe of sepal-length and sepal category
pd.concat((SEPAL_LENGTH_SERIES, sepal_length_ef_binning), axis=1)

    sepal.length   sepal.length
0            5.1  Sedikit Lebar
1            4.9  Sedikit Lebar
2            4.7  Sedikit Lebar
3            4.6  Sedikit Lebar
4            5.0  Sedikit Lebar
..           ...            ...
145          6.7   Sangat Lebar
146          6.3          Lebar
147          6.5   Sangat Lebar
148          6.2          Lebar
149          5.9          Lebar

[150 rows x 2 columns]

In [67]:
# equal-frequency intervals binning with label
labelled_sepal_length_ef_binning

Lebar            56
Sedikit Lebar    52
Sangat Lebar     42
Name: sepal.length, dtype: int64

In [68]:
# equal-frequency intervals out label
interval_sepal_length_ef_binning

(5.4, 6.3]                   56
(4.2989999999999995, 5.4]    52
(6.3, 7.9]                   42
Name: sepal.length, dtype: int64

###### Petal Length

* Equal Frequency Intervals panjang mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [69]:
# equal-frequency intervals

labels = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
amount_of_binning = len(labels)

petal_length_ef_binning = pd.qcut(PETAL_LENGTH_SERIES, amount_of_binning, labels)
labelled_petal_length_ef_binning = petal_length_ef_binning.value_counts()
interval_petal_length_ef_binning = pd.qcut(PETAL_LENGTH_SERIES, amount_of_binning).value_counts()

In [70]:
# dataframe of petal-length and petal category
pd.concat((PETAL_LENGTH_SERIES, petal_length_ef_binning), axis=1)

    petal.length   petal.length
0            1.4  Sedikit Lebar
1            1.4  Sedikit Lebar
2            1.3  Sedikit Lebar
3            1.5  Sedikit Lebar
4            1.4  Sedikit Lebar
..           ...            ...
145          5.2   Sangat Lebar
146          5.0   Sangat Lebar
147          5.2   Sangat Lebar
148          5.4   Sangat Lebar
149          5.1   Sangat Lebar

[150 rows x 2 columns]

In [71]:
# equal-frequency intervals binning with label
labelled_petal_length_ef_binning

Lebar            54
Sedikit Lebar    50
Sangat Lebar     46
Name: petal.length, dtype: int64

In [72]:
# equal-frequency intervals out label
interval_petal_length_ef_binning

(2.633, 4.9]      54
(0.999, 2.633]    50
(4.9, 6.9]        46
Name: petal.length, dtype: int64

#### 3. Lakukan proses diskritisasi dengan basis *entropy*

**ENTROPY**

Diskritisasi berbasis entropi (entropy based discretization) adalah salah satu jenis algoritma diskritisasi terawasi yang menggunakan mekanisme top- down. Tujuan dari algoritma ini adalah mendapatkan partisi yang mengandung baris data dari kelas yang sama sebanyak mungkin.

* RUMUS ENTROPY

  ![image.png](https://cdn.mathpix.com/snip/images/T3MAnkOgvu54ASi68sQ5fR96rPCLPxjYofOqC9L4IpM.original.fullsize.png)

* RUMUS GAIN

  ![image.png](https://cdn.mathpix.com/snip/images/T6pg-dpJKT4PsSKzNdI_sQWFKj1kZao_9Oaf5-Zf88g.original.fullsize.png)

* RUMUS INFO
  
  ![image.png](https://cdn.mathpix.com/snip/images/iFDk6peaL_uAebWnVWZebfy9CvJ0VNADb8ukE2Nmyds.original.fullsize.png)

Menambahkan sempel data yang akan di hitung

In [75]:
sample = df[["sepal.length"]]
sample.describe()

       sepal.length
count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000

Membuat kategori secara random untuk data sempel

In [76]:
np.random.seed(0)
sample["kategori"] = np.where(np.random.choice(2,sample.shape[0]) < 1,"A","B")
sample

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

     sepal.length kategori
0             5.1        A
1             4.9        B
2             4.7        B
3             4.6        A
4             5.0        B
..            ...      ...
145           6.7        A
146           6.3        B
147           6.5        B
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

Membuat fungsi GetOverollCategory (keseluruhan) yang digunakan untuk menghitung data keseluruhan yang nantinya digunakan untuk menghitung entropy

In [77]:
def GetOverollCategory(col):
  group = sample.loc[:, :].groupby("kategori").count()
  a = group.loc["A", col]
  b = group.loc["B", col]
  return (a,b,a+b)

Memasukan fungsi splitter yang digunakan untuk membuat split antara value yang telah ditentukan lalu mengembalikan data yang telah dipisahkan

In [78]:
def splitter(value, col):
  #get data less and greater from value
  less = sample[sample[col] <= value]
  greater = sample[sample[col] > value]

  #calculate into category for each data
  less_group = less.loc[:, :].groupby("kategori").count()
  greater_group = greater.loc[:, :].groupby("kategori").count()

  #get value based on category
  less_category_A = less_group.loc["A",col]
  less_category_B = less_group.loc["B",col]
  greater_category_A = greater_group.loc["A",col]
  greater_category_B = greater_group.loc["B",col]

  return (
      [less_category_A, less_category_B, less_category_A + less_category_B],
      [greater_category_A, greater_category_B, greater_category_A + greater_category_B]
  )

Membuat fungsi entropy untuk melakukan perhitungan entropy

In [79]:
def entropy (d):
  r1 = (d[0] / d[2]) * np.log2(d[0] / d[2])
  r2 = (d[1] / d[2]) * np.log2(d[1] / d[2])
  return np.sum([r1, r2]) * -1

Membuat fungsi info dan gain

In [80]:
def info(d):
  r1 = (d[0][2] / sample.shape[0]) * entropy(d[0])
  r2 = (d[1][2] / sample.shape[0]) * entropy(d[1])
  return r1 + r2

Fungsi gain untuk menghitung selisih antara entropy awal dengan yang baru

In [81]:
def gain(Einitial, Enew):
  return Einitial - Enew

Membuat Dinitial

In [83]:
D = GetOverollCategory("sepal.length")
entropy_d = entropy(D)
print(D)
print(entropy_d)

(68, 82, 150)
0.993707106604508

Melakukan beberapa fungsi split untuk mendapatkan informasi yang terbaik

##### SPLIT 1 : 4.5

In [84]:
split1 = splitter(4.5, "sepal.length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.0069930419733333915

##### SPLIT 2 : 5.2

In [85]:
split1 = splitter(5.2, "sepal.length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.025783795927140973

##### SPLIT 3 : 7.5

In [86]:
split1 = splitter(7.5, "sepal.length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.0017898381837971877

Split terbaik yaitu split 3 yang memberikan keuntungan informasi sebesar 0.0017898381837971877 karena yang paling rendah